# This is a basic workflow to help you get started with Actions

name: CI for partsunlimited

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Setup NuGet.exe
        uses: NuGet/setup-nuget@v1.0.5
      - name: setup-msbuild
        uses: microsoft/setup-msbuild@v1
      - name: NuGet restore
        run: nuget restore
    
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: drop
          path: partsunlimited/PartsUnlimited-aspnet45/src/PartsUnlimitedWebsite/

 
      

      
